---
- name: Restart Docker Service
  hosts: all
  become: yes
  tasks:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
     - name: Run docker-compose up
      command: sudo docker-compose up 
      args:
        chdir: /home/ubuntu/easyTravel-Docker

