---
- name: Restart Docker Service
  hosts: all
  become: yes
  tasks:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
    - name: Start Docker
      service:
        name: docker
        state: started
