---
- name: Run Docker Compose
  hosts: 54.179.62.102
  become: yes
  tasks:
    - name: Change to project directory
      ansible.builtin.shell: cd /path/to/your/docker-compose/project && docker-compose up -d
      args:
        chdir: /path/to/your/docker-compose/project
